"""Initial schema

Revision ID: ea4a6621450b
Revises: 
Create Date: 2025-11-11 23:15:20.736999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4a6621450b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('population_year', sa.Integer(), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('government_type', sa.String(length=50), nullable=True),
    sa.Column('fiscal_year_end_month', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_end_day', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_charter_city', sa.Boolean(), nullable=True),
    sa.Column('has_bankruptcy_history', sa.Boolean(), nullable=False),
    sa.Column('bankruptcy_filing_date', sa.Date(), nullable=True),
    sa.Column('bankruptcy_exit_date', sa.Date(), nullable=True),
    sa.Column('bankruptcy_chapter', sa.String(length=20), nullable=True),
    sa.Column('bankruptcy_notes', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('finance_department_url', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities')),
    sa.UniqueConstraint('name', name=op.f('uq_cities_name'))
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reliability_rating', sa.String(length=20), nullable=True),
    sa.Column('reliability_notes', sa.Text(), nullable=True),
    sa.Column('access_method', sa.String(length=50), nullable=False),
    sa.Column('requires_authentication', sa.Boolean(), nullable=False),
    sa.Column('expected_update_frequency', sa.String(length=50), nullable=True),
    sa.Column('last_checked_date', sa.Date(), nullable=True),
    sa.Column('last_available_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources'))
    )
    op.create_table('expenditure_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_level1', sa.String(length=100), nullable=False),
    sa.Column('category_level2', sa.String(length=100), nullable=True),
    sa.Column('category_level3', sa.String(length=100), nullable=True),
    sa.Column('standard_name', sa.String(length=255), nullable=False),
    sa.Column('is_personnel_cost', sa.Boolean(), nullable=False),
    sa.Column('is_pension_cost', sa.Boolean(), nullable=False),
    sa.Column('is_debt_service', sa.Boolean(), nullable=False),
    sa.Column('is_capital', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenditure_categories')),
    sa.UniqueConstraint('standard_name', name=op.f('uq_expenditure_categories_standard_name'))
    )
    op.create_table('projection_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(length=100), nullable=False),
    sa.Column('scenario_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projection_scenarios'))
    )
    op.create_table('revenue_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_level1', sa.String(length=100), nullable=False),
    sa.Column('category_level2', sa.String(length=100), nullable=True),
    sa.Column('category_level3', sa.String(length=100), nullable=True),
    sa.Column('standard_name', sa.String(length=255), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('is_discretionary', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revenue_categories')),
    sa.UniqueConstraint('standard_name', name=op.f('uq_revenue_categories_standard_name'))
    )
    op.create_table('risk_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_code', sa.String(length=50), nullable=False),
    sa.Column('indicator_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('calculation_formula', sa.Text(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('threshold_healthy', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('threshold_adequate', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('threshold_warning', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('threshold_critical', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('higher_is_better', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=255), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_indicators')),
    sa.UniqueConstraint('indicator_code', name=op.f('uq_risk_indicators_indicator_code'))
    )
    op.create_table('data_lineage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_document_url', sa.String(length=500), nullable=True),
    sa.Column('source_document_page', sa.Integer(), nullable=True),
    sa.Column('source_document_section', sa.String(length=255), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=False),
    sa.Column('extracted_by', sa.String(length=255), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('validated_by', sa.String(length=255), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('cross_validated_source_id', sa.Integer(), nullable=True),
    sa.Column('matches_cross_validation', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cross_validated_source_id'], ['data_sources.id'], name=op.f('fk_data_lineage_cross_validated_source_id_data_sources')),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_data_lineage_source_id_data_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_lineage'))
    )
    op.create_index('ix_data_lineage_record', 'data_lineage', ['table_name', 'record_id'], unique=False)
    op.create_table('fiscal_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('cafr_available', sa.Boolean(), nullable=False),
    sa.Column('cafr_url', sa.String(length=500), nullable=True),
    sa.Column('cafr_publish_date', sa.Date(), nullable=True),
    sa.Column('cafr_audit_firm', sa.String(length=255), nullable=True),
    sa.Column('cafr_audit_opinion', sa.String(length=50), nullable=True),
    sa.Column('budget_available', sa.Boolean(), nullable=False),
    sa.Column('budget_url', sa.String(length=500), nullable=True),
    sa.Column('budget_adopted_date', sa.Date(), nullable=True),
    sa.Column('calpers_valuation_available', sa.Boolean(), nullable=False),
    sa.Column('calpers_valuation_url', sa.String(length=500), nullable=True),
    sa.Column('calpers_valuation_date', sa.Date(), nullable=True),
    sa.Column('revenues_complete', sa.Boolean(), nullable=False),
    sa.Column('expenditures_complete', sa.Boolean(), nullable=False),
    sa.Column('pension_data_complete', sa.Boolean(), nullable=False),
    sa.Column('data_quality_score', sa.Integer(), nullable=True),
    sa.Column('data_quality_notes', sa.Text(), nullable=True),
    sa.Column('validated_by', sa.String(length=255), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_fiscal_years_city_id_cities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fiscal_years')),
    sa.UniqueConstraint('city_id', 'year', name='uq_fiscal_year_city_year')
    )
    op.create_index('ix_fiscal_year_city_year', 'fiscal_years', ['city_id', 'year'], unique=False)
    op.create_table('risk_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('indicator_code', sa.String(length=50), nullable=False),
    sa.Column('analysis_date', sa.DateTime(), nullable=False),
    sa.Column('years_analyzed', sa.Integer(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('trend_direction', sa.String(length=20), nullable=False),
    sa.Column('trend_slope', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('trend_significance', sa.String(length=20), nullable=True),
    sa.Column('average_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('min_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('volatility', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_risk_trends_city_id_cities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_trends')),
    sa.UniqueConstraint('city_id', 'indicator_code', 'analysis_date', name='uq_risk_trend')
    )
    op.create_index('ix_risk_trend_city', 'risk_trends', ['city_id'], unique=False)
    op.create_table('scenario_assumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('assumption_category', sa.String(length=50), nullable=False),
    sa.Column('assumption_name', sa.String(length=100), nullable=False),
    sa.Column('assumption_value', sa.String(length=100), nullable=False),
    sa.Column('assumption_numeric_value', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['projection_scenarios.id'], name=op.f('fk_scenario_assumptions_scenario_id_projection_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_assumptions')),
    sa.UniqueConstraint('scenario_id', 'assumption_category', 'assumption_name', name='uq_scenario_assumption')
    )
    op.create_table('benchmark_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('indicator_code', sa.String(length=50), nullable=False),
    sa.Column('city_value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('peer_group_name', sa.String(length=100), nullable=False),
    sa.Column('peer_group_size', sa.Integer(), nullable=True),
    sa.Column('peer_average', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('peer_median', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('peer_25th_percentile', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('peer_75th_percentile', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('peer_best', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('peer_worst', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('city_percentile', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('comparison_category', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_benchmark_comparisons_city_id_cities')),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], name=op.f('fk_benchmark_comparisons_fiscal_year_id_fiscal_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmark_comparisons'))
    )
    op.create_index('ix_benchmark_comparison_city', 'benchmark_comparisons', ['city_id'], unique=False)
    op.create_index('ix_benchmark_comparison_fiscal_year', 'benchmark_comparisons', ['fiscal_year_id'], unique=False)
    op.create_table('expenditures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('fund_type', sa.String(length=50), nullable=False),
    sa.Column('fund_name', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('variance_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('variance_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source_document_type', sa.String(length=50), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_line_item', sa.String(length=255), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('estimation_method', sa.String(length=255), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('actual_amount >= 0', name=op.f('ck_expenditures_ck_expenditure_actual_non_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['expenditure_categories.id'], name=op.f('fk_expenditures_category_id_expenditure_categories')),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], name=op.f('fk_expenditures_fiscal_year_id_fiscal_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenditures')),
    sa.UniqueConstraint('fiscal_year_id', 'category_id', 'fund_type', name='uq_expenditure_year_category_fund')
    )
    op.create_index('ix_expenditure_category', 'expenditures', ['category_id'], unique=False)
    op.create_index('ix_expenditure_fiscal_year', 'expenditures', ['fiscal_year_id'], unique=False)
    op.create_table('financial_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('base_fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('projection_year', sa.Integer(), nullable=False),
    sa.Column('years_ahead', sa.Integer(), nullable=False),
    sa.Column('projection_date', sa.DateTime(), nullable=False),
    sa.Column('projection_model_version', sa.String(length=20), nullable=False),
    sa.Column('total_revenues_projected', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('recurring_revenues_projected', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('revenue_growth_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('total_expenditures_projected', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('personnel_costs_projected', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('pension_costs_projected', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('opeb_costs_projected', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('other_costs_projected', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('base_expenditure_growth_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('pension_growth_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('operating_surplus_deficit', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('operating_margin_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('beginning_fund_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ending_fund_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fund_balance_ratio', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('is_deficit', sa.Boolean(), nullable=False),
    sa.Column('is_depleting_reserves', sa.Boolean(), nullable=False),
    sa.Column('reserves_below_minimum', sa.Boolean(), nullable=False),
    sa.Column('is_fiscal_cliff', sa.Boolean(), nullable=False),
    sa.Column('pension_funded_ratio_projected', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('pension_ual_projected', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['base_fiscal_year_id'], ['fiscal_years.id'], name=op.f('fk_financial_projections_base_fiscal_year_id_fiscal_years')),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_financial_projections_city_id_cities')),
    sa.ForeignKeyConstraint(['scenario_id'], ['projection_scenarios.id'], name=op.f('fk_financial_projections_scenario_id_projection_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_projections')),
    sa.UniqueConstraint('city_id', 'base_fiscal_year_id', 'projection_year', 'scenario_id', name='uq_financial_projection')
    )
    op.create_index('ix_financial_projection_base_year', 'financial_projections', ['base_fiscal_year_id'], unique=False)
    op.create_index('ix_financial_projection_city', 'financial_projections', ['city_id'], unique=False)
    op.create_index('ix_financial_projection_year', 'financial_projections', ['projection_year'], unique=False)
    op.create_table('fiscal_cliff_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('base_fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.DateTime(), nullable=False),
    sa.Column('has_fiscal_cliff', sa.Boolean(), nullable=False),
    sa.Column('fiscal_cliff_year', sa.Integer(), nullable=True),
    sa.Column('years_until_cliff', sa.Integer(), nullable=True),
    sa.Column('reserves_exhausted_year', sa.Integer(), nullable=True),
    sa.Column('cumulative_deficit_at_cliff', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('revenue_increase_needed_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('expenditure_decrease_needed_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['base_fiscal_year_id'], ['fiscal_years.id'], name=op.f('fk_fiscal_cliff_analyses_base_fiscal_year_id_fiscal_years')),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_fiscal_cliff_analyses_city_id_cities')),
    sa.ForeignKeyConstraint(['scenario_id'], ['projection_scenarios.id'], name=op.f('fk_fiscal_cliff_analyses_scenario_id_projection_scenarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fiscal_cliff_analyses')),
    sa.UniqueConstraint('city_id', 'base_fiscal_year_id', 'scenario_id', name='uq_fiscal_cliff_analysis')
    )
    op.create_table('fund_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('fund_type', sa.String(length=50), nullable=False),
    sa.Column('fund_name', sa.String(length=255), nullable=True),
    sa.Column('nonspendable', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('restricted', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('committed', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('assigned', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('unassigned', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_fund_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fund_balance_ratio', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('days_of_cash', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('yoy_change_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('yoy_change_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source_document_type', sa.String(length=50), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], name=op.f('fk_fund_balances_fiscal_year_id_fiscal_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fund_balances')),
    sa.UniqueConstraint('fiscal_year_id', 'fund_type', name='uq_fund_balance_year_fund')
    )
    op.create_index('ix_fund_balance_fiscal_year', 'fund_balances', ['fiscal_year_id'], unique=False)
    op.create_table('opeb_liabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('total_opeb_liability', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('plan_fiduciary_net_position', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_opeb_liability', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('funded_ratio', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('opeb_expense', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_contributions', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('healthcare_cost_trend', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], name=op.f('fk_opeb_liabilities_fiscal_year_id_fiscal_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opeb_liabilities')),
    sa.UniqueConstraint('fiscal_year_id', name='uq_opeb_fiscal_year')
    )
    op.create_index('ix_opeb_fiscal_year', 'opeb_liabilities', ['fiscal_year_id'], unique=False)
    op.create_table('pension_assumption_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effective_fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('assumption_type', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.String(length=100), nullable=True),
    sa.Column('new_value', sa.String(length=100), nullable=False),
    sa.Column('impact_on_liability', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('impact_on_funded_ratio', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('announced_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['effective_fiscal_year_id'], ['fiscal_years.id'], name=op.f('fk_pension_assumption_changes_effective_fiscal_year_id_fiscal_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pension_assumption_changes'))
    )
    op.create_table('pension_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('budgeted_contribution', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_contribution', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('variance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('normal_cost_paid', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ual_payment_paid', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], name=op.f('fk_pension_contributions_fiscal_year_id_fiscal_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pension_contributions')),
    sa.UniqueConstraint('fiscal_year_id', 'plan_name', name='uq_pension_contribution')
    )
    op.create_index('ix_pension_contribution_fiscal_year', 'pension_contributions', ['fiscal_year_id'], unique=False)
    op.create_table('pension_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=True),
    sa.Column('active_members', sa.Integer(), nullable=True),
    sa.Column('retired_members', sa.Integer(), nullable=True),
    sa.Column('total_members', sa.Integer(), nullable=True),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('total_pension_liability', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('service_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('interest_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('fiduciary_net_position', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('actual_investment_return', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_investment_return_percent', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('net_pension_liability', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('unfunded_actuarial_liability', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('funded_ratio', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('employer_normal_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('employer_normal_cost_percent', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('ual_payment', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_employer_contribution', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_employer_contribution_percent', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('employee_contribution', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('covered_payroll', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('inflation_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('payroll_growth_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('mortality_table', sa.String(length=100), nullable=True),
    sa.Column('amortization_period_years', sa.Integer(), nullable=True),
    sa.Column('amortization_method', sa.String(length=50), nullable=True),
    sa.Column('projected_contribution_next_year', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('projected_contribution_rate_next_year', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('is_preliminary', sa.Boolean(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('funded_ratio >= 0 AND funded_ratio <= 2.0', name=op.f('ck_pension_plans_ck_pension_funded_ratio_reasonable')),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], name=op.f('fk_pension_plans_fiscal_year_id_fiscal_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pension_plans')),
    sa.UniqueConstraint('fiscal_year_id', 'plan_name', name='uq_pension_plan_year_name')
    )
    op.create_index('ix_pension_plan_fiscal_year', 'pension_plans', ['fiscal_year_id'], unique=False)
    op.create_table('pension_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('projection_year', sa.Integer(), nullable=False),
    sa.Column('projected_contribution', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('projected_contribution_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('projected_payroll', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('projected_normal_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('projected_ual_payment', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('scenario', sa.String(length=50), nullable=False),
    sa.Column('assumed_discount_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('assumed_investment_return', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('assumed_payroll_growth', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['base_fiscal_year_id'], ['fiscal_years.id'], name=op.f('fk_pension_projections_base_fiscal_year_id_fiscal_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pension_projections')),
    sa.UniqueConstraint('base_fiscal_year_id', 'plan_name', 'projection_year', 'scenario', name='uq_pension_projection')
    )
    op.create_index('ix_pension_projection_base_year', 'pension_projections', ['base_fiscal_year_id'], unique=False)
    op.create_index('ix_pension_projection_year', 'pension_projections', ['projection_year'], unique=False)
    op.create_table('revenues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('fund_type', sa.String(length=50), nullable=False),
    sa.Column('fund_name', sa.String(length=255), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('variance_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('variance_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('source_document_type', sa.String(length=50), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_line_item', sa.String(length=255), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('estimation_method', sa.String(length=255), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('actual_amount >= 0', name=op.f('ck_revenues_ck_revenue_actual_non_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['revenue_categories.id'], name=op.f('fk_revenues_category_id_revenue_categories')),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], name=op.f('fk_revenues_fiscal_year_id_fiscal_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revenues')),
    sa.UniqueConstraint('fiscal_year_id', 'category_id', 'fund_type', name='uq_revenue_year_category_fund')
    )
    op.create_index('ix_revenue_category', 'revenues', ['category_id'], unique=False)
    op.create_index('ix_revenue_fiscal_year', 'revenues', ['fiscal_year_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('calculation_date', sa.DateTime(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('liquidity_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('structural_balance_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pension_stress_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('revenue_sustainability_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('debt_burden_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('data_completeness_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('indicators_available', sa.Integer(), nullable=False),
    sa.Column('indicators_missing', sa.Integer(), nullable=False),
    sa.Column('data_as_of_date', sa.DateTime(), nullable=False),
    sa.Column('data_age_months', sa.Integer(), nullable=True),
    sa.Column('top_risk_factors', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('validated_by', sa.String(length=255), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('overall_score >= 0 AND overall_score <= 100', name=op.f('ck_risk_scores_ck_risk_overall_score_valid')),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['fiscal_years.id'], name=op.f('fk_risk_scores_fiscal_year_id_fiscal_years')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_scores')),
    sa.UniqueConstraint('fiscal_year_id', 'calculation_date', name='uq_risk_score_fy_date')
    )
    op.create_index('ix_risk_score_date', 'risk_scores', ['calculation_date'], unique=False)
    op.create_index('ix_risk_score_fiscal_year', 'risk_scores', ['fiscal_year_id'], unique=False)
    op.create_table('risk_indicator_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_score_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('indicator_value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('indicator_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('threshold_category', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('contribution_to_overall', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('data_source_table', sa.String(length=100), nullable=True),
    sa.Column('data_source_record_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['risk_indicators.id'], name=op.f('fk_risk_indicator_scores_indicator_id_risk_indicators')),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], name=op.f('fk_risk_indicator_scores_risk_score_id_risk_scores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_indicator_scores')),
    sa.UniqueConstraint('risk_score_id', 'indicator_id', name='uq_risk_indicator_score')
    )
    op.create_index('ix_risk_indicator_score_indicator', 'risk_indicator_scores', ['indicator_id'], unique=False)
    op.create_index('ix_risk_indicator_score_risk_score', 'risk_indicator_scores', ['risk_score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_risk_indicator_score_risk_score', table_name='risk_indicator_scores')
    op.drop_index('ix_risk_indicator_score_indicator', table_name='risk_indicator_scores')
    op.drop_table('risk_indicator_scores')
    op.drop_index('ix_risk_score_fiscal_year', table_name='risk_scores')
    op.drop_index('ix_risk_score_date', table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index('ix_revenue_fiscal_year', table_name='revenues')
    op.drop_index('ix_revenue_category', table_name='revenues')
    op.drop_table('revenues')
    op.drop_index('ix_pension_projection_year', table_name='pension_projections')
    op.drop_index('ix_pension_projection_base_year', table_name='pension_projections')
    op.drop_table('pension_projections')
    op.drop_index('ix_pension_plan_fiscal_year', table_name='pension_plans')
    op.drop_table('pension_plans')
    op.drop_index('ix_pension_contribution_fiscal_year', table_name='pension_contributions')
    op.drop_table('pension_contributions')
    op.drop_table('pension_assumption_changes')
    op.drop_index('ix_opeb_fiscal_year', table_name='opeb_liabilities')
    op.drop_table('opeb_liabilities')
    op.drop_index('ix_fund_balance_fiscal_year', table_name='fund_balances')
    op.drop_table('fund_balances')
    op.drop_table('fiscal_cliff_analyses')
    op.drop_index('ix_financial_projection_year', table_name='financial_projections')
    op.drop_index('ix_financial_projection_city', table_name='financial_projections')
    op.drop_index('ix_financial_projection_base_year', table_name='financial_projections')
    op.drop_table('financial_projections')
    op.drop_index('ix_expenditure_fiscal_year', table_name='expenditures')
    op.drop_index('ix_expenditure_category', table_name='expenditures')
    op.drop_table('expenditures')
    op.drop_index('ix_benchmark_comparison_fiscal_year', table_name='benchmark_comparisons')
    op.drop_index('ix_benchmark_comparison_city', table_name='benchmark_comparisons')
    op.drop_table('benchmark_comparisons')
    op.drop_table('scenario_assumptions')
    op.drop_index('ix_risk_trend_city', table_name='risk_trends')
    op.drop_table('risk_trends')
    op.drop_index('ix_fiscal_year_city_year', table_name='fiscal_years')
    op.drop_table('fiscal_years')
    op.drop_index('ix_data_lineage_record', table_name='data_lineage')
    op.drop_table('data_lineage')
    op.drop_table('risk_indicators')
    op.drop_table('revenue_categories')
    op.drop_table('projection_scenarios')
    op.drop_table('expenditure_categories')
    op.drop_table('data_sources')
    op.drop_table('cities')
    # ### end Alembic commands ###
